name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Provision Kubernetes cluster
        run: |
          # Install KinD
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

          # Create KinD cluster
          kind create cluster --config kind-config.yaml

      - name: Deploy Ingress Controller
        run: |
          # Install Nginx Ingress Controller
          kubectl apply -f nginx-ingress.yaml

      - name: Deploy HTTP-Echo deployments
        run: |
          kubectl apply -f bar-deployment.yaml
          kubectl apply -f foo-deployment.yaml

      - name: Configure Cluster/Ingress Routing
        run: |
          # Modify /etc/hosts file
          echo "$(kubectl cluster-info | grep 'Kubernetes master' | awk '{print $NF}') foo.localhost bar.localhost" | sudo tee -a /etc/hosts

      - name: Check Health of Ingress and Deployments
        run: |
          # Wait for Ingress controller to be ready
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller -n ingress-nginx

          # Wait for deployments to be ready
          kubectl wait --for=condition=available deployment/bar-deployment
          kubectl wait --for=condition=available deployment/foo-deployment

      - name: Generate Load of Randomized Traffic
        run: |
          # Run your load testing script (e.g., using Apache Bench)
          ab -n 100 -c 10 -H "Host: foo.localhost" http://localhost/
          ab -n 100 -c 10 -H "Host: bar.localhost" http://localhost/

      - name: Capture Load Testing Result
        run: |
          # Capture and process the load testing results

      - name: Post Load Testing Result as Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub API or CLI to post a comment on the pull request
